Apps/Ak__Main__/urls.py
from django.urls import path
# View Function Base
from .views import home_page, contact_us, product_detail, category_detail, shop_page, product_ajax_filter, \
    comment_for_product, rating_for_product, checkout, about_us, Send_Payment_Gateway_Request, Verify_Gate_Way_Request
from Apps.SiteSettings_Apps__Ak.RenderPartial.views import remove_product_from_cart

app_name = "Ak_Main"
urlpatterns = [
    path('', home_page, name="Home_Page"),
    path('contact-us/', contact_us, name="contact-us"),
    path('product/<slug:slug>', product_detail, name="product-detail"),
    path('category/<slug:slug>', category_detail, name="category-detail"),
    path('shop/', shop_page, name="shop_page"),
    path('ajax-filter/', product_ajax_filter, name="product_ajax_filter"),
    path('send-comment/<slug:slug>', comment_for_product, name="product_comment"),
    path('send-rating/<slug:slug>', rating_for_product, name="product_rating"),
    path('remove-product-from-cart', remove_product_from_cart, name="remove_product_from_cart"),
    path('checkout', checkout, name="checkout"),
    path('about-us/', about_us, name="about_us"),
    # ----Gateway----
    path('send-request/', Send_Payment_Gateway_Request, name="send_gate_way_request"),
    path('verify/', Verify_Gate_Way_Request, name="verify_gate_way_request"),

]

Apps/Usrs_Apps__Ak/Ak_User_Account_Dashboard/urls.py
from django.urls import path
# Views
from .views import Dashboard, change_user_information, logout_user

app_name = 'Ak_User_Account_Dashboard'
urlpatterns = [
    path('user/dashboard/', Dashboard, name="User_Dashboard"),
    path('user/change_user_information/', change_user_information,name="changer_user_information"),
    path("user/logout/", logout_user, name="logout_user"),
]

Arzan_Kala/urls.py
# Module Static Files
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # Include Urls
    path('', include("Apps.Ak__Main__.urls", namespace="Ak_Main")),
    # Include Admin Panel Url
    path('manager/', include("Apps.AdminSite__Ak.AdminPanel.urls", namespace='AdminSite__Ak')),
    # Include User Apps Url
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account.urls", namespace="Ak_User_Account")),
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account_Dashboard.urls", namespace="Ak_User_Account_Dashboard")),
    # Include Product Apps Url
    path('', include('Apps.Product_Apps__Ak.urls', namespace="Ak_Product_Apps")),
    # Django Social Auth
    path('', include('social_django.urls', namespace='social')),
    # GetWay Urls
    # path('', include('pay_ir.api.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Usrs_Apps__Ak/Ak_User_Account_Dashboard/models.py
from django.db import models

# Create your models here.

Apps/Usrs_Apps__Ak/Ak_User_Account_Dashboard/forms.py
from django import forms


class Activation_link_submission_form(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())


class Change_User_Information(forms.Form):
    gender_selection_choices = [
        ('MS', 'زن'),
        ('MR', 'مرد'),
        ('TG', 'دیگر'),
    ]

    first_name = forms.CharField(required=False, max_length=150, widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    last_name = forms.CharField(required=False, max_length=150, widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    user_profile = forms.ImageField(required=False, widget=forms.FileInput(attrs={
        "class": "d-none"
    }))
    gender_selection = forms.ChoiceField(required=False, choices=gender_selection_choices, widget=forms.Select(attrs={
        "class": "form-control"
    }))
    postal_code = forms.CharField(required=False, max_length=10, widget=forms.TextInput(attrs={
        "class": "form-control"
    }))
    phone_number = forms.CharField(required=False, max_length=11, widget=forms.NumberInput(attrs={
        "class": "form-control"
    }))
    location_first = forms.CharField(required=False, max_length=250, widget=forms.Textarea(attrs={
        "class": "form-control"
    }))

Apps/Usrs_Apps__Ak/Ak_User_Account_Dashboard/views.py
from django.shortcuts import render, reverse, redirect
from django.http import JsonResponse
from .forms import Activation_link_submission_form
# Dectrators Login Requierd
from django.contrib.auth.decorators import login_required
# User Model
from django.contrib.auth.models import User
from .forms import Change_User_Information
from Apps.Usrs_Apps__Ak.Ak_User_Account.models import Profile
from django.contrib.auth import logout

# Create your views here.

from Apps.Usrs_Apps__Ak.Ak_User_Account.views import Send_account_activation_link


@login_required()
def Dashboard(request, *args, **kwargs):
    context = {

    }
    return render(request=request, template_name='User_Apps/Ak_User_Account_Dashboard/dashboard.html', context=context)


@login_required()
def change_user_information(request):
    if not request.is_ajax():
        return redirect("Ak_Main:Home_Page")
    Change__User__Information = Change_User_Information(request.POST or None, request.FILES or None, initial={
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "user_profile": request.user.profile.user_profile,
        "gender_selection": request.user.profile.gender_selection,
        "postal_code": request.user.profile.postal_code,
        "phone_number": request.user.profile.phone_number,
        "location_first": request.user.profile.location_first,
    })

    if Change__User__Information.is_valid():
        try:
            request.user.first_name = Change__User__Information.cleaned_data.get("first_name")
            request.user.last_name = Change__User__Information.cleaned_data.get("last_name")
            request.user.profile.user_profile = Change__User__Information.cleaned_data.get("user_profile")
            request.user.profile.gender_selection = Change__User__Information.cleaned_data.get("gender_selection")
            request.user.profile.postal_code = Change__User__Information.cleaned_data.get("postal_code")
            request.user.profile.phone_number = Change__User__Information.cleaned_data.get("gender_selection")
            request.user.profile.location_first = Change__User__Information.cleaned_data.get("location_first")
            request.user.save()
            request.user.profile.save()
        except Exception as Err:
            return JsonResponse({
                "status": 203,
                "message": "لطفا فیلد هارا با دقت چک کنید و راهنمای آنهارا بررسی کنید..."
            })
        return JsonResponse({
            "status": 200,
            "message": "اطلاعات شما با موفقیت بروزرسانی شد"
        })
    elif Change__User__Information.errors:
        return JsonResponse(Change__User__Information.errors, safe=False)
    return render(request, "User_Apps/Ak_User_Account_Dashboard/change-user-information-form.html", context={
        "Change__User__Information": Change__User__Information
    })


@login_required()
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('Ak_Main:Home_Page')

templates/User_Apps/Ak_User_Account_Dashboard/__main__.html
{% load static %}
<!--Render Partial Tag-->
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta -->
   {% include 'All_Template_Main/Header_Main/Meta_Tags_Header_Main__.html' %}
    <!-- SITE TITLE -->
    <title>ARZAN KALA |
    {% block title_home_page %}{% endblock %}

    </title>
   {% include 'All_Template_Main/Header_Main/CSS_Refrence_Header_Main__.html' %}
</head>

<body dir="rtl">

<!-- LOADER -->
<div class="preloader">
    <div class="lds-ellipsis">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
<!-- END LOADER -->

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">به سایت ارزان کالا خوش آمدید</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-justify custom-text-welcome-modal">
                سلام کاربر عزیز
                <span class="custom-fullname-welcome-modal">
              محمد حاصل مهری
          </span>
                <br>
                ضمن خوش آمد گویی برای ثبت نام شما در این سایت ما پیوندی را به ایمیل شما ( sectech.ir@gamil.com ) جهت
                تایید حساب کاربری ارسال کرده ایم،
                <br>
                لطفا روی پیوند ارسال شده کلیک کنید و همچنین از قسمت پنل کاربری اطلاعات خود را تکمیل نمایید.
                <br>
                توجه داشته باشید تا زمانی که حساب کاربری خود را تایید نکنید قادر به خرید محصول در این سایت نخواهید بود.
                <br>
                اگر ایمیل تایید حساب کاربری را در قسمت inbox مشاهده نکردید به قسمت هرزنامه ها مراجعه کنید،
                <br>
                <span class="custom-warn-welcome-modal-2">
              چنانچه در قسمت هرزنامه ها هم موفق به دریافت نشدید از پنل کاربری روی گزینه ارسال مجدد لینک فعال سازی حساب کاربری کلیک کنید.
                </span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-outline-danger" data-dismiss="modal">خروج</button>
            </div>
        </div>
    </div>
</div>
<!--End Modal-->

<!-- START HEADER -->
{% block dashboard_header %}{% endblock %}
<!-- END HEADER -->

{#--BreadCrupb--#}
{% block breadcrumb_dashboard %}{% endblock %}


<!-- START SECTION BANNER -->
<!-- END SECTION BANNER -->

<!-- END MAIN CONTENT -->
<div class="main_content">
{% block dashboard_content %}{% endblock %}
</div>
<!-- END MAIN CONTENT -->

<!-- START FOOTER -->
{% render_partial 'Apps.SiteSettings_Apps__Ak.RenderPartial.views.Footer' %}
<!-- END FOOTER -->

<a href="#" class="scrollup" style="display: none;"><i class="ion-ios-arrow-up"></i></a>

{% block dashboard_script %}{% endblock %}
{# Toaster Component Js #}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</body>

</html>

templates/User_Apps/Ak_User_Account_Dashboard/change-user-information-form.html
<form action="" autocomplete="off" id="user-information-form">
    {% csrf_token %}
    <div class="row">
         <div class="form-group col-md-12">
            {{ Change__User__Information.user_profile }}
             <span id="user-profile-box" class="d-flex m-auto rounded justify-content-center align-items-center" style="height: 8rem !important;width: 8rem !important;border: 1px dotted rgba(43,47,76,0.3) !important;">
                 <i class="fa fa-camera" style="font-size: 4rem !important;color: rgba(43,47,76,0.3)"></i>
             </span>
        </div>
        <div class="form-group col-md-6">
            <label>نام <span class="required">*</span></label>
            {{ Change__User__Information.first_name }}
        </div>
        <div class="form-group col-md-6">
            <label>نام خانوادگی <span class="required">*</span></label>
            {{ Change__User__Information.last_name }}
        </div>
        <div class="form-group col-md-12">
            <label>انتخاب جنسیت <span class="required">*</span></label>
            {{ Change__User__Information.gender_selection }}
        </div>
        <div class="form-group col-md-12">
            <label>کد پستی <span class="required">*</span></label>
            {{ Change__User__Information.postal_code }}
        </div>
        <div class="form-group col-md-12">
            <label>تلفن همراه<span class="required">*</span></label>
            {{ Change__User__Information.phone_number }}
        </div>
        <div class="form-group col-md-12">
            <label>آدرس <span class="required">*</span></label>
            {{ Change__User__Information.location_first }}
        </div>
        <div class="col-md-12">
            <button type="button" class="btn btn-fill-out" name="submit" value="Submit">ذخیره</button>
        </div>
    </div>
</form>

templates/User_Apps/Ak_User_Account_Dashboard/dashboard.html
{% extends 'User_Apps/Ak_User_Account_Dashboard/__main__.html' %}
{% load static %}
<!--Render Partial Tag-->
{% load render_partial %}


<!-- START HEADER -->
{% block dashboard_header %}
    <header class="header_wrap fixed-top header_with_topbar">
        {#    <!-- Start Top Menu-->#}
        {% render_partial 'Apps.SiteSettings_Apps__Ak.RenderPartial.views.header_one' %}
        {#    <!-- End Top Menu-->#}
    </header>
{% endblock %}
<!-- END HEADER -->

<!-- START SECTION BREADCRUMB -->
{% block breadcrumb_dashboard %}
    <div class="breadcrumb_section bg_gray page-title-mini">
        <div class="container"><!-- STRART CONTAINER -->
            <div class="row align-items-center">
                <div class="col-md-6">
                    <div class="page-title">
                        <h1>حساب کاربری</h1>
                    </div>
                </div>
                <div class="col-md-6">
                    <ol class="breadcrumb justify-content-md-end">
                        <li class="breadcrumb-item"><a href="{% url 'Ak_Main:Home_Page' %}">خانه</a></li>
                        <li class="breadcrumb-item active">حساب کاربری</li>
                    </ol>
                </div>
            </div>
        </div><!-- END CONTAINER-->
    </div>
{% endblock %}
<!-- END SECTION BREADCRUMB -->

<!-- START MAIN CONTENT -->
{% block dashboard_content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <div class="dashboard_menu">
                        <ul class="nav nav-tabs flex-column" role="tablist">
                            <li class="nav-item" style="background-color: #f7f8fb !important;">
                                <img src="{{ user.profile.user_profile.url }}" alt=""
                                     class="rounded-circle mx-auto d-flex my-2" width="100">
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" id="dashboard-tab" data-toggle="tab" href="#dashboard"
                                   role="tab"
                                   aria-controls="dashboard" aria-selected="false"><i
                                        class="ti-layout-grid2"></i>داشبورد</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="orders-tab" data-toggle="tab" href="#orders" role="tab"
                                   aria-controls="orders" aria-selected="false"><i class="ti-shopping-cart-full"></i>سفارشات</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="address-tab" data-toggle="tab" href="#address" role="tab"
                                   aria-controls="address" aria-selected="true"><i class="ti-location-pin"></i>آدرس
                                    من</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="account-detail-tab" data-toggle="tab" href="#account-detail"
                                   role="tab" aria-controls="account-detail" aria-selected="true"><i
                                        class="ti-id-badge"></i>جزئیات حساب</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'Ak_User_Account_Dashboard:logout_user' %}"><i
                                        class="ti-lock"></i>خروج</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9 col-md-8">
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="dashboard" role="tabpanel"
                             aria-labelledby="dashboard-tab">
                            <div class="card">
                                <div class="card-header">
                                    <h3>داشبورد</h3>
                                </div>
                                <div class="card-body">
                                    <p>از داشبورد حساب شما. می توانید سفارشات اخیر خود را به راحتی بررسی کرده و مشاهده
                                        کنید.</p>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
                            <div class="card">
                                <div class="card-header">
                                    <h3>سفارشات</h3>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>سفارش</th>
                                                <th>تاریخ</th>
                                                <th>وضعیت</th>
                                                <th>جمع</th>
                                                <th>اقدامات</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for cart in user.cart_set.all %}
                                                {% if cart.active %}
                                                    <tr>
                                                        <td>#1234</td>
                                                        <td>{{ cart.pay_time }}</td>
                                                        <td>پرداخت شده</td>
                                                        <td>{{ cart.total_product_price }} تومان</td>
                                                        <td><a href="#" class="btn btn-fill-out btn-sm">نمایش</a></td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="address" role="tabpanel" aria-labelledby="address-tab">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="card mb-3 mb-lg-0">
                                        <div class="card-header">
                                            <h3>آدرس شما</h3>
                                        </div>
                                        <div class="card-body">
                                            <address>{{ user.profile.location_first }}</address>
                                            <p>{{ user.profile.postal_code|default:"آدرسی ثبت نشده است" }}</p>
                                            <a href="#" class="btn btn-fill-out disabled">ویرایش</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="account-detail" role="tabpanel"
                             aria-labelledby="account-detail-tab">
                            <div class="card">
                                <div class="card-header">
                                    <h3>جزئیات حساب</h3>
                                </div>
                                <div class="card-body" id="change-user-information-section">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- START SECTION SUBSCRIBE NEWSLETTER -->
    {% include 'All_Template_Main/Content/Subscribe_News_Letters.html' %}
    <!-- START SECTION SUBSCRIBE NEWSLETTER -->

{% endblock %}
<!-- END MAIN CONTENT -->

<!--Js Refrences-->
{% block dashboard_script %}
    <script src="{% static 'site_assets/js/jquery-1.12.4.min.js' %}"></script>
    {#    <!-- jquery-ui -->#}
    <script src="{% static 'site_assets/js/jquery-ui.js' %}"></script>
    {#    <!-- popper min js -->#}
    <script src="{% static 'site_assets/js/popper.min.js' %}"></script>
    {#    <!-- Latest compiled and minified Bootstrap -->#}
    <script src="{% static 'site_assets/bootstrap/js/bootstrap.min.js' %}"></script>
    {#    <!-- owl-carousel min js  -->#}
    <script src="{% static 'site_assets/owlcarousel/js/owl.carousel.min.js' %}"></script>
    {#    <!-- magnific-popup min js  -->#}
    <script src="{% static 'site_assets/js/magnific-popup.min.js' %}"></script>
    {#    <!-- waypoints min js  -->#}
    <script src="{% static 'site_assets/js/waypoints.min.js' %}"></script>
    {#    <!-- parallax js  -->#}
    <script src="{% static 'site_assets/js/parallax.js' %}"></script>
    {#    <!-- countdown js  -->#}
    <script src="{% static 'site_assets/js/jquery.countdown.min.js' %}"></script>
    {#    <!-- imagesloaded js -->#}
    <script src="{% static 'site_assets/js/imagesloaded.pkgd.min.js' %}"></script>
    {#    <!-- isotope min js -->#}
    <script src="{% static 'site_assets/js/isotope.min.js' %}"></script>
    {#    <!-- jquery.dd.min js -->#}
    <script src="{% static 'site_assets/js/jquery.dd.min.js' %}"></script>
    {#    <!-- slick js -->#}
    <script src="{% static 'site_assets/js/slick.min.js' %}"></script>
    {#    <!-- elevatezoom js -->#}
    <script src="{% static 'site_assets/js/jquery.elevatezoom.js' %}"></script>
    {#    <!-- scripts js -->#}
    <script src="{% static 'site_assets/js/scripts.js' %}"></script>
    {# Ajax #}
    <script src="{% static 'site_assets/js/ajax/user-dashboard.js' %}"></script>
{% endblock %}