Apps/AdminSite__Ak/AdminPanel/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    # -- User Apps
    list_user_view,
    edit_user_view,
    show_user_view,
    delete_user_view,
    advanced_user_filter_view,

    # Products App
    products_list_view,
    create_product_view,
    add_more_img_product,
    create_tag_view,
    create_category_view,
    search_tag_view,
    search_category_view,
    search_brand_view,
    advanced_product_filter,
    invoice_display,
    deleted_product_view,
    search_slider_view,
    create_brand_view,
    create_slider_view,

    # Site Settings
    view_settings,
    customizer_theme,

    # Email Management
    email_management,
    creating_sending_mail,
    remove_mail,

    # Edit User
    save_information_edit_user,

    # Create User
    default_user_form_view,
    user_information_form_view,

    LoginAdmin,
    LogOut_Admin_View,
    IndexView,

    # Wallet
    WALLET_VIEW,

    # Comment List
    Comment_List,
)

app_name = 'AdminSite__Ak'
urlpatterns = [
    # Users Page App
    path('user/users-list', list_user_view, name='list_users_view'),
    path('user/edit-user/<int:pk>', edit_user_view, name='edit_user_view'),
    path('user/save-information/<int:pk>', save_information_edit_user, name='save_information_edit_user_view'),
    path('user/view-user/<int:pk>', show_user_view, name='show_user_view'),
    path('user/user-info-form/<int:pk>', user_information_form_view, name='user_information_form_view'),
    path('user/default-user-form/', default_user_form_view, name='default_user_form_view'),
    path('user/delete-user/', delete_user_view, name='delete_user_form_view'),
    path('user/advanced-user-filter/', advanced_user_filter_view, name='advanced_user_filter'),
    # --------------------------------------------------------------------
    # Products Page App
    path('products/products-list/', products_list_view, name='products_list_view'),
    path('product/create-product/', create_product_view, name='create_product_view'),
    path('product/add-more-pr-img/', add_more_img_product, name='add_more_img_product_view'),
    path('product/create-tag/', create_tag_view, name='create_tag_view'),
    path('product/create-category/', create_category_view, name='create_category_view'),
    path('product/create-brand/', create_brand_view, name='create_brand_view'),
    path('product/create-slider/', create_slider_view, name='create_slider_view'),
    path('search-tag/', search_tag_view, name='search_tag_view'),
    path('search-category/', search_category_view, name='search_category_view'),
    path('search-live-brand/', search_brand_view, name='search_brand_view'),
    path('search-live-slider/', search_slider_view, name='search_slider_view'),
    path('advanced-product-filter/', advanced_product_filter, name="advanced-product-filter-view"),
    path('product/invoice/<int:id>', invoice_display, name="product_invoice_display"),
    path('deleted-product/', deleted_product_view, name="deleted_product_view"),
    # --------------------------------------------------------------------
    # Site Settings App
    path('settings/', view_settings, name='settings_view'),
    path('customize/', customizer_theme, name='customize_theme'),
    # --------------------------------------------------------------------
    # Email Management
    path('email-management/', email_management, name="email_management_view"),
    path('send-mail/', creating_sending_mail, name="creating_sending_mail_view"),
    path("removed-mail/", remove_mail, name="removed_mail_view"),

    # Wallet View
    path("wallet/", WALLET_VIEW, name="wallet_view"),

    # Comment List
    path('comment-list/', Comment_List, name='Comment_List'),

    path('', IndexView, name='dashboard'),
    path('login/', LoginAdmin, name='AdminAuth'),
    path('logout/', LogOut_Admin_View, name='admin_logout'),
]

from .forms.authentication_form import ResetPasswordAdmin, SetNewAdminPassword

urlpatterns += [
    # ...
    # Forget Password
    path('reset-password/',
         auth_views.PasswordResetView.as_view(
             template_name='AdminPanel/Auth/password_reset_form.html',
             subject_template_name='AdminPanel/Auth/password_reset_subject.txt',
             email_template_name='AdminPanel/Auth/password_reset_email.html',
             form_class=ResetPasswordAdmin,
             success_url=reverse_lazy('AdminSite__Ak:password_reset_done'),
         ),
         name='password_reset'
         ),

    path('manager/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='AdminPanel/Auth/password_reset_done.html'
         ),

         name='password_reset_done'),
    path('manager/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='AdminPanel/Auth/password_reset_confirm.html',
             form_class=SetNewAdminPassword,
             success_url=reverse_lazy('AdminSite__Ak:password_reset_complete')

         ),

         name='password_reset_confirm'),
    path('manager/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='AdminPanel/Auth/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

Apps/Ak__Main__/urls.py
from django.urls import path
# View Function Base
from .views import home_page, contact_us, product_detail, category_detail, shop_page, product_ajax_filter, \
    comment_for_product, rating_for_product, checkout, about_us, Send_Payment_Gateway_Request, Verify_Gate_Way_Request
from Apps.SiteSettings_Apps__Ak.RenderPartial.views import remove_product_from_cart

app_name = "Ak_Main"
urlpatterns = [
    path('', home_page, name="Home_Page"),
    path('contact-us/', contact_us, name="contact-us"),
    path('product/<slug:slug>', product_detail, name="product-detail"),
    path('category/<slug:slug>', category_detail, name="category-detail"),
    path('shop/', shop_page, name="shop_page"),
    path('ajax-filter/', product_ajax_filter, name="product_ajax_filter"),
    path('send-comment/<slug:slug>', comment_for_product, name="product_comment"),
    path('send-rating/<slug:slug>', rating_for_product, name="product_rating"),
    path('remove-product-from-cart', remove_product_from_cart, name="remove_product_from_cart"),
    path('checkout', checkout, name="checkout"),
    path('about-us/', about_us, name="about_us"),
    # ----Gateway----
    path('send-request/', Send_Payment_Gateway_Request, name="send_gate_way_request"),
    path('verify/', Verify_Gate_Way_Request, name="verify_gate_way_request"),

]

Arzan_Kala/urls.py
# Module Static Files
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # Include Urls
    path('', include("Apps.Ak__Main__.urls", namespace="Ak_Main")),
    # Include Admin Panel Url
    path('manager/', include("Apps.AdminSite__Ak.AdminPanel.urls", namespace='AdminSite__Ak')),
    # Include User Apps Url
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account.urls", namespace="Ak_User_Account")),
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account_Dashboard.urls", namespace="Ak_User_Account_Dashboard")),
    # Include Product Apps Url
    path('', include('Apps.Product_Apps__Ak.urls', namespace="Ak_Product_Apps")),
    # Django Social Auth
    path('', include('social_django.urls', namespace='social')),
    # GetWay Urls
    # path('', include('pay_ir.api.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/All_Template_Main/Footer/Footer_Black_Main.html
{% load static %}
<footer class="footer_dark">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="widget">
                        <div class="footer_logo">
                            <a href="#"><img src="{{ ObjSiteSettings.WhiteLogoSiteFooter.url }}" alt="logo"/></a>
                        </div>
                        <!--Start Short Description Footer-->
                        <p>
                            {{ ObjSiteSettings.ShortDescriptionFooter }}
                        </p>
                        <!--End Short Description Footer-->
                    </div>
                    <div class="widget">
                        <ul class="social_icons social_white">
                            <li><a target="_blank" href="{{ ObjSiteSettings.FacebookSite }}"><i class="ion-social-facebook"></i></a></li>
                            <li><a target="_blank" href="{{ ObjSiteSettings.TwitterSite }}"><i class="ion-social-twitter"></i></a></li>
                            <li><a target="_blank" href="{{ ObjSiteSettings.TelegramSite }}"><i class="ion-social-googleplus"></i></a></li>
                            <li><a target="_blank" href="{{ ObjSiteSettings.YoutubeSite }}"><i class="ion-social-youtube-outline"></i></a></li>
                            <li><a target="_blank" href="{{ ObjSiteSettings.InstagramSite }}"><i class="ion-social-instagram-outline"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="widget">
                        <h6 class="widget_title">لینک های مفید</h6>
                        <ul class="widget_links">
                            <li><a href="#">درباره ما</a></li>
                            <li><a href="{% url 'Ak_Main:contact-us' %}">تماس با ما</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-2 col-md-6 col-sm-6">
                    <div class="widget">
                        <h6 class="widget_title">حساب کاربری</h6>
                        <ul class="widget_links">
                            <li><a href="{% url 'AdminSite__Ak:dashboard' %}">حساب من</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="widget">
                        <h6 class="widget_title">اطلاعات تماس</h6>
                        <ul class="contact_info contact_info_light">
                            <li>
                                <i class="ti-location-pin"></i>
                                <p>{{ ObjSiteSettings.CompanyAddress }}</p>
                            </li>
                            <li>
                                <i class="ti-email"></i>
                                <a href="mailto:info@sitename.com">{{ ObjSiteSettings.EmailSupportSite }}</a>
                            </li>
                            <li>
                                <i class="ti-mobile"></i>
                                <p>{{ ObjSiteSettings.SiteSupportContactNumber }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom_footer border-top-tran">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-md-0 text-center text-md-left">{{ ObjSiteSettings.CopyrightText }}</p>
                </div>
                <div class="col-md-6">
                    <ul class="footer_payment text-center text-lg-right">
                        <script id='payir-trust-script' src='https://cdn.pay.ir/js/trust-logo.js' data-id='207096' data-logo='1'></script>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/All_Template_Main/Footer/Info_Card_Footer.html
<div class="middle_footer">
    <div class="custom-container">
        <div class="row">
            <div class="col-12">
                <div class="shopping_info">
                    <div class="row justify-content-center">
                        <div class="col-md-4">
                            <div class="icon_box icon_box_style2">
                                <div class="icon">
                                    <i class="flaticon-shipped"></i>
                                </div>
                                <div class="icon_box_content">
                                    <h5>تخفیف های ویژه</h5>
                                    <p>دارای تخفیف های ویژه برای محصولات پرفروش</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="icon_box icon_box_style2">
                                <div class="icon">
                                    <i class="flaticon-money-back"></i>
                                </div>
                                <div class="icon_box_content">
                                    <h5>30 روز ضمانت بازگشت</h5>
                                    <p>محصولات در صورت وجود مشکل دارای ضمانت برگشت میباشند</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="icon_box icon_box_style2">
                                <div class="icon">
                                    <i class="flaticon-support"></i>
                                </div>
                                <div class="icon_box_content">
                                    <h5>پشتیبانی 24 ساعته</h5>
                                    <p>مدیران ما در هر لحظه آماده پاسخگویی به مشکلات شما</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>