Apps/AdminSite__Ak/AdminPanel/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    # -- User Apps
    list_user_view,
    edit_user_view,
    show_user_view,
    delete_user_view,
    advanced_user_filter_view,

    # Products App
    products_list_view,
    create_product_view,
    add_more_img_product,
    create_tag_view,
    create_category_view,
    search_tag_view,
    search_category_view,
    search_brand_view,
    advanced_product_filter,
    invoice_display,
    deleted_product_view,
    search_slider_view,
    create_brand_view,
    create_slider_view,

    # Site Settings
    view_settings,
    customizer_theme,

    # Email Management
    email_management,
    creating_sending_mail,
    remove_mail,

    # Edit User
    save_information_edit_user,

    # Create User
    default_user_form_view,
    user_information_form_view,

    LoginAdmin,
    LogOut_Admin_View,
    IndexView,

    # Wallet
    WALLET_VIEW,

    # Comment List
    Comment_List,
)

app_name = 'AdminSite__Ak'
urlpatterns = [
    # Users Page App
    path('user/users-list', list_user_view, name='list_users_view'),
    path('user/edit-user/<int:pk>', edit_user_view, name='edit_user_view'),
    path('user/save-information/<int:pk>', save_information_edit_user, name='save_information_edit_user_view'),
    path('user/view-user/<int:pk>', show_user_view, name='show_user_view'),
    path('user/user-info-form/<int:pk>', user_information_form_view, name='user_information_form_view'),
    path('user/default-user-form/', default_user_form_view, name='default_user_form_view'),
    path('user/delete-user/', delete_user_view, name='delete_user_form_view'),
    path('user/advanced-user-filter/', advanced_user_filter_view, name='advanced_user_filter'),
    # --------------------------------------------------------------------
    # Products Page App
    path('products/products-list/', products_list_view, name='products_list_view'),
    path('product/create-product/', create_product_view, name='create_product_view'),
    path('product/add-more-pr-img/', add_more_img_product, name='add_more_img_product_view'),
    path('product/create-tag/', create_tag_view, name='create_tag_view'),
    path('product/create-category/', create_category_view, name='create_category_view'),
    path('product/create-brand/', create_brand_view, name='create_brand_view'),
    path('product/create-slider/', create_slider_view, name='create_slider_view'),
    path('search-tag/', search_tag_view, name='search_tag_view'),
    path('search-category/', search_category_view, name='search_category_view'),
    path('search-live-brand/', search_brand_view, name='search_brand_view'),
    path('search-live-slider/', search_slider_view, name='search_slider_view'),
    path('advanced-product-filter/', advanced_product_filter, name="advanced-product-filter-view"),
    path('product/invoice/<int:id>', invoice_display, name="product_invoice_display"),
    path('deleted-product/', deleted_product_view, name="deleted_product_view"),
    # --------------------------------------------------------------------
    # Site Settings App
    path('settings/', view_settings, name='settings_view'),
    path('customize/', customizer_theme, name='customize_theme'),
    # --------------------------------------------------------------------
    # Email Management
    path('email-management/', email_management, name="email_management_view"),
    path('send-mail/', creating_sending_mail, name="creating_sending_mail_view"),
    path("removed-mail/", remove_mail, name="removed_mail_view"),

    # Wallet View
    path("wallet/", WALLET_VIEW, name="wallet_view"),

    # Comment List
    path('comment-list/', Comment_List, name='Comment_List'),

    path('', IndexView, name='dashboard'),
    path('login/', LoginAdmin, name='AdminAuth'),
    path('logout/', LogOut_Admin_View, name='admin_logout'),
]

from .forms.authentication_form import ResetPasswordAdmin, SetNewAdminPassword

urlpatterns += [
    # ...
    # Forget Password
    path('reset-password/',
         auth_views.PasswordResetView.as_view(
             template_name='AdminPanel/Auth/password_reset_form.html',
             subject_template_name='AdminPanel/Auth/password_reset_subject.txt',
             email_template_name='AdminPanel/Auth/password_reset_email.html',
             form_class=ResetPasswordAdmin,
             success_url=reverse_lazy('AdminSite__Ak:password_reset_done'),
         ),
         name='password_reset'
         ),

    path('manager/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='AdminPanel/Auth/password_reset_done.html'
         ),

         name='password_reset_done'),
    path('manager/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='AdminPanel/Auth/password_reset_confirm.html',
             form_class=SetNewAdminPassword,
             success_url=reverse_lazy('AdminSite__Ak:password_reset_complete')

         ),

         name='password_reset_confirm'),
    path('manager/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='AdminPanel/Auth/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

Arzan_Kala/urls.py
# Module Static Files
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # Include Urls
    path('', include("Apps.Ak__Main__.urls", namespace="Ak_Main")),
    # Include Admin Panel Url
    path('manager/', include("Apps.AdminSite__Ak.AdminPanel.urls", namespace='AdminSite__Ak')),
    # Include User Apps Url
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account.urls", namespace="Ak_User_Account")),
    path('', include("Apps.Usrs_Apps__Ak.Ak_User_Account_Dashboard.urls", namespace="Ak_User_Account_Dashboard")),
    # Include Product Apps Url
    path('', include('Apps.Product_Apps__Ak.urls', namespace="Ak_Product_Apps")),
    # Django Social Auth
    path('', include('social_django.urls', namespace='social')),
    # GetWay Urls
    # path('', include('pay_ir.api.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/AdminSite__Ak/AdminPanel/models.py
from django.db import models
from ckeditor.fields import RichTextField, CKEditorWidget
from django.contrib.auth.models import User
from Arzan_Kala.Extentions import Jalali_date_converter


class Customize_Theme(models.Model):
    CHOICES_COLOR = [
        ('PR', 'بنفش'),
        ('GR', 'سبز'),
        ('RD', 'قرمز'),
        ('BL', 'آبی'),
        ('OG', 'نارنجی'),
        ('BC', 'مشکی'),
    ]
    CHOICES_THEME = [
        ('LT', 'روشن'),
        ('DK', 'تاریک'),
        ('ST', 'نیمه روشن'),
    ]
    CHOICES_MENU_MODE = [
        ('CD', 'بسته'),
        ('ON', 'باز'),
    ]
    CHOICES_COLOR_HEADER = [
        ('WT', 'سفید'),
        ('PR', 'بنفش'),
        ('GR', 'سبز'),
        ('RD', 'قرمز'),
        ('BL', 'آبی'),
        ('OG', 'نارنجی'),
        ('BC', 'مشکی'),
    ]
    CHOICES_HEADER_MODE = [
        ('HN', 'مخفی'),
        ('FD', 'ثابت'),
        ('SG', 'چسبیده'),
        ('FG', 'شناور'),
    ]
    CHOICES_FOOTER_MODE = [
        ('HN', 'مخفی'),
        ('FD', 'ثابت'),
        ('SG', 'چسبیده'),
    ]
    menu_color = models.CharField(verbose_name="رنگ منو", choices=CHOICES_COLOR, default='BL', max_length=2)
    theme_color = models.CharField(verbose_name='رنگ تم', choices=CHOICES_THEME, default='LT', max_length=2)
    menu_mode = models.BooleanField(verbose_name='حالت منو', default=False)
    header_color = models.CharField(verbose_name='رنگ سربرگ', choices=CHOICES_COLOR_HEADER, default='WT', max_length=2)
    header_mode = models.CharField(verbose_name='حالت سربرگ', choices=CHOICES_HEADER_MODE, default='FG', max_length=2)
    footer_mode = models.CharField(verbose_name='حالت پاورقی', choices=CHOICES_FOOTER_MODE, default='FD', max_length=2)
    flash_navigation_mode = models.BooleanField(verbose_name='حالت فلش پیمایش صفحه', default=True)


class Email_Management(models.Model):
    user = models.ManyToManyField(User)
    subject = models.CharField(max_length=200)
    html_content = RichTextField(config_name='Email_Management_Config', max_length=2800)
    send_date = models.DateTimeField(null=True, blank=True)
    number_of_submissions = models.BigIntegerField(blank=True, null=True)

    @property
    def Jalali_send_date(self):
        return Jalali_date_converter(self.send_date)

    def save(self, *args, **kwargs):
        return super(Email_Management, self).save(*args, **kwargs)


from .signals import edit_email_management_field

Apps/AdminSite__Ak/AdminPanel/forms/authentication_form.py
from django import forms

# Form Auth
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User


class AdminAuthLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "id": "user-name",
                "placeholder": "نام کاربری",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "user-password",
                "placeholder": "کلمه عبور",
            }
        )
    )


class ResetPasswordAdmin(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'id': 'email-account',
                'placeholder': 'لطفا ایمیل حساب کاربری خود را وارد نمایید...'
            }
        )
    )


class SetNewAdminPassword(SetPasswordForm):
    new_password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "new-password",
                "placeholder": "لطفا رمز عبور جدید را وارد نمایید...",
            }
        )
    )
    new_password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "id": "confirm-new-password",
                "placeholder": "لطفا رمز عبور جدید را مجدد وارد نمایید...",
            }
        )
    )

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get("new_password1")
        new_password2 = self.cleaned_data.get("new_password2")
        if new_password1 != new_password2:
            raise forms.ValidationError("رمز های عبور همسان نیستند!")
        else:
            return new_password2

Apps/AdminSite__Ak/AdminPanel/forms/customizer_theme_form.py
from django import forms
from Apps.AdminSite__Ak.AdminPanel.models import Customize_Theme


class customizer_theme_form(forms.ModelForm):
    class Meta:
        model = Customize_Theme
        fields='__all__'
        widgets = {
            'menu_color': forms.Select(attrs={
                'class': 'd-none'
            }),
            'theme_color': forms.Select(attrs={
                'class': 'd-none'
            }),
            'menu_mode': forms.CheckboxInput(attrs={
                'class': 'd-none'
            }),
            'header_color': forms.Select(attrs={
                'class': 'd-none'
            }),
            'header_mode': forms.Select(attrs={
                'class': 'd-none'
            }),
            'footer_mode': forms.Select(attrs={
                'class': 'd-none'
            }),
            'flash_navigation_mode': forms.CheckboxInput(attrs={
                'class': 'd-none'
            }),
        }

Apps/AdminSite__Ak/AdminPanel/forms/email_management.py
from django import forms
from Apps.AdminSite__Ak.AdminPanel.models import Email_Management


class Email_Management_Form(forms.ModelForm):
    class Meta:
        model = Email_Management
        exclude = (
            'send_date',
            'number_of_submissions'
        )
        widgets = {
            'user': forms.SelectMultiple(attrs={
                "class": "select2 form-control"
            }),
            'subject': forms.TextInput(attrs={
                "class": "form-control"
            }),
        }


class remove_mail_form(forms.Form):
    removed_mail_id = forms.CharField()

templates/AdminPanel/Email-Management/creating-sending-mail.html
{% extends 'AdminPanel/__Main__/base.html' %}
{% load static %}
{% load render_partial %}

<!-- BEGIN: Vendor CSS-->
{% block vendor_css_creating_sending_mail%}
    {# Select 2 #}
    <link rel="stylesheet" type="text/css" href="{% static 'AdminPanel/app-assets/vendors/css/forms/select/select2.min.css' %}">
{% endblock %}

{% block content_creating_sending_email %}
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-body">
                <div class="card border-info text-center bg-transparent">
                    <div class="card-content">
                        <div class="card-body">
                            <h4 class="card-title mt-3">ورود جدید</h4>
                            <form action="" method="POST">
                                {% csrf_token %}
                                 <div class="form-label-group mt-1">
                                <div class="form-group">
                                    {{ Email_Management__Form.user }}
                                </div>
                                <label for="id_user">به</label>
                            </div>
                            <div class="form-label-group">
                                {{ Email_Management__Form.subject }}
                                <label for="emailSubject">موضوع</label>
                            </div>
                            <div id="email-container">
                                {{ Email_Management__Form.html_content }}
                            </div>
                            <div class="form-group">
                                <button type="submit" id="send-mail" class="btn btn-block btn-success mt-1">ارسال ایمیل</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- BEGIN: Page Vendor JS-->
{% block page_vendor_js_creating_sending_mail %}
    {# Select 2 #}
    <script src="{% static 'AdminPanel/app-assets/vendors/js/forms/select/select2.full.min.js' %}"></script>
{% endblock %}


<!-- BEGIN: Page JS-->
{% block page_js_creating_sending_mail %}
    {# Select 2 #}
    <script src="{% static 'AdminPanel/app-assets/js/scripts/forms/select/form-select2.min.js' %}"></script>
    {# Page Js Ck Editor #}
        <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
        <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}

templates/AdminPanel/Email-Management/mail-msg.html
<div class="email-scroll-area">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="email-label ml-2 my-2 pl-1">
                                                <span class="mr-1 bullet bullet-primary bullet-sm"></span><small class="mail-label">شرکت</small>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="card px-1">
                                                <div class="card-header email-detail-head ml-75">
                                                    <div class="user-details d-flex justify-content-between align-items-center flex-wrap">
                                                        <div class="avatar mr-75">
                                                            <img src="{% if Email_Msg.user.all.count == 1 %}{{ Email_Msg.user.first.profile.user_profile.url }}{% endif %}" alt="avtar img holder" width="61" height="61">
                                                        </div>
                                                        <div class="mail-items">
                                                            <h4 class="list-group-item-heading mb-0">{% if Email_Msg.user.all.count == 1 %}{{ Email_Msg.user.first.get_full_name }}{% endif %}</h4>
                                                            <div class="email-info-dropup dropdown">
                                        <span class="dropdown-toggle font-small-3" id="dropdownMenuButton{{ Email_Msg.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                          abaldersong@utexas.edu
                                        </span>
                                                                <div class="dropdown-menu dropdown-menu-right p-50" aria-labelledby="dropdownMenuButton{{ Email_Msg.id }}">
                                                                    <div class="px-25 dropdown-item">از جانب:<strong> abaldersong@utexas.edu </strong></div>
                                                                    <div class="px-25 dropdown-item">به:<strong> johndoe@ow.ly </strong></div>
                                                                    <div class="px-25 dropdown-item">تاریخ:<strong>{{ Email_Msg.send_date }}</strong></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="mail-meta-item">
                                                        <div class="mail-time mb-1">4:14 قبل از ظهر</div>
                                                        <div class="mail-date">17 مرداد 1398</div>
                                                    </div>
                                                </div>
                                                <div class="card-body mail-message-wrapper pt-2 mb-0">
                                                    <div class="mail-message">
                                                        {{ Email_Msg.html_content|safe }}
                                                    </div>
                                                    <div class="mail-attachements d-flex">
                                                        <i class="feather icon-paperclip font-medium-5 mr-50"></i>
                                                        <span>پیوست ها</span>
                                                    </div>
                                                </div>
                                                <div class="mail-files py-2">
                                                    <div class="chip chip-primary">
                                                        <div class="chip-body py-50">
                                                            <span class="chip-text">interdum.docx</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="card">
                                                <div class="card-body">
                                                    <div class="d-flex justify-content-between">
                                                        <span class="font-medium-1">اینجا را کلیک کنید<span class="primary cursor-pointer"><strong>پاسخ</strong></span>  یا<span class="primary  cursor-pointer"><strong> رو به جلو</strong></span></span>
                                                        <i class="feather icon-paperclip font-medium-5 mr-50"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

templates/AdminPanel/Email-Management/removed-mail-form.html
<form class="d-none" action="" method="post" id="removed-mail-form">
    {% csrf_token %}
</form>

templates/AdminPanel/Email-Management/template-user-mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ Subject }}</title>
</head>
<body>
{{ Content|safe }}
</body>
</html>